micronaut:
  application:
    name: APIVersioningDemo
  router:
    versioning:
      enabled: true
      default-version: 1
      parameter:
        enabled: true
        names: 'v,api-version'
      header:
        enabled: true
        names:
          - 'X-API-VERSION'
          - 'Accept-Version'
netty:
  default:
    allocator:
      max-order: 3
